default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: ""
  host: localhost

development:
  <<: *default
  database: my_api_app_development

test:
  <<: *default
  database: my_api_app_test

production:
  <<: *default
  database: my_api_app_production
  username: my_api_app
  password: <%= ENV['MY_API_APP_DATABASE_PASSWORD'] %>